### ISSUE TITLE
System does not clear the values on the completion of a Maintenance session.

### ISSUE THREAD

**Issue by SivasankariSubramaniam** [luwenshuo/PT05_SCMWorkshop2#1]
[ChangeRequestForm-DefectFix_CR0018.docx](https://github.com/luwenshuo/PT05_SCMWorkshop2/files/1269331/ChangeRequestForm-DefectFix_CR0018.docx)

The system does not reset the values for “Show Total Cash Held” and “Press to Collect Cash” when Maintainer successfully pushes “Press Here When Finished”. These values are persisted when a re-login happens.

Updated CR number

**Comment by vikramNus** [comment]
new bug - we need to work to fix this .. cancelling all team members vacation until this bug is fixed

**Comment by vikramNus** [comment]
This is very critical defect , users are unhappy . Team Lets do this fix

**Comment by e0015350** [comment]
[ChangeRequestForm_DefectFix.docx]
Updated impact analysis and technical Evaluation

**Comment by vikramNus** [comment]
Thanks Naw Win Win Latt(E0015365 ) for updating CHange request from with your Technical impact analysis. 
Looks good to me , Approved !!
 Go Ahead  to update the code for this enhancement in the Branch "bugfix-issue1"

**Comment by vikramNus** [comment]
Thanks e0015350 for updating CHange request from with your Technical impact analysis.
Looks good to me , Approved !!
Go Ahead to update the code for this bug in the Branch "bugfix-issue1"

**Comment by vikramNus** [comment]
Thanks e0015350 for updating CHange request from with your Technical impact analysis.
Looks good to me , Approved !!
Go Ahead to update the code for this bug in the Branch "bugfix-issue1"

**Comment by vikramNus** [comment]
Luwenshou you can pull the dev branch into Release branch for testing

**Comment by vikramNus** [comment]
virendra5 start testing

**Comment by virendra5** [comment]
Test Case 
1. “Show Total Cash Held” : Passed
2. “Press to Collect Cash” when Maintainer successfully pushes : Passed
3. “Press Here When Finished” : Passed
