### ISSUE TITLE
Enhance collection with cash denomination

### ISSUE THREAD

**Issue by E0015365** [luwenshuo/PT05_SCMWorkshop2#2]
[ChangeRequestForm-Enhancement_CR0005.docx](https://github.com/luwenshuo/PT05_SCMWorkshop2/files/1269242/ChangeRequestForm-Enhancement_CR0005.docx)

**Comment by E0015365** [comment]
[ChangeRequestForm-Enhancement_CR0017.docx](https://github.com/luwenshuo/PT05_SCMWorkshop2/files/1269272/ChangeRequestForm-Enhancement_CR0017.docx)

Updating the version number

**Comment by vikramNus** [comment]
Thanks Naw Win Win Latt(E0015365 ) for updating CHange request from with your technical impact analysis

**Comment by E0015365** [comment]
Added Impact assessment
[ChangeRequestForm-Enhancement_CR0017.docx](https://github.com/luwenshuo/PT05_SCMWorkshop2/files/1269367/ChangeRequestForm-Enhancement_CR0017.docx)

**Comment by E0015365** [comment]
[ChangeRequestForm-Enhancement_CR0017.docx](https://github.com/luwenshuo/PT05_SCMWorkshop2/files/1269376/ChangeRequestForm-Enhancement_CR0017.docx)
Updated the document assignee

**Comment by vikramNus** [comment]
Thanks E0015365 & e0015350  for updating CHange request from with your technical impact analysis.
Looks good to me , Approved !!
Go Ahead to update the code for this enhancement in the Branch "feature-issue2"
[ChangeRequestForm-Enhancement_CR0017.docx](https://github.com/luwenshuo/PT05_SCMWorkshop2/files/1269405/ChangeRequestForm-Enhancement_CR0017.docx)

**Comment by virendra5** [comment]
Hi Naw, "Enhance collection with cash denomination changes are checked in", please review the changes

**Comment by vikramNus** [comment]
SivasankariSubramaniam start testing

**Comment by SivasankariSubramaniam** [comment]
Bug Fixed. Please screenshot.
![bug_fix_ 1](https://user-images.githubusercontent.com/17666706/29959581-9f2d8466-8f2a-11e7-82c3-825ccb65c0dc.png)
